#' Number of in-frame P-sites per coding sequence.
#'
#' This function generates a data table that for each transcript contains at
#' least i) its name; ii) the length of its coding sequence; iii) the number of
#' in-frame P-sites falling in its annotated coding sequence (if any) for all
#' samples. A chosen number of nucleotides at the beginning and/or at the end of
#' the CDSs can be excluded for restricting the analysis to a portion of the
#' original coding sequence. In this case the output data table includes an
#' additional column reporting the length of the selected region. Please note:
#' transcripts without annotated CDS are automatically discarded.
#'
#' @param data List of data tables from \code{\link{psite_info}}.
#' @param annotation Data table as generated by \code{\link{create_annotation}}.
#' @param start_nts Positive integer specifying the number of nucleotides at the
#'   beginning of the coding sequences to be excluded from the analisys. Default
#'   is 0.
#' @param stop_nts Positive integer specifying the number of nucleotides at the
#'   end of the coding sequences to be excluded from the analisys. Default is 0.
#' @return A data table.
#' @examples
#' data(reads_psite_list)
#' data(mm81cdna)
#'
#' ## Compute the number of in-frame P-sites per whole coding sequence.
#' psite_cds <- cds_coverage(reads_psite_list, mm81cdna)
#'
#' ## Compute the number of in-frame P-sites per the coding sequence exluding
#' ## the first 15 nucleotides and the last 10 nucleotides.
#' psite_cds <- cds_coverage(reads_psite_list, mm81cdna, start_nts = 15, stop_nts = 10)
#' @import data.table
#' @export
cds_coverage <- function(data, annotation, start_nts = 0, stop_nts = 0) {

  psite_cds <- annotation[l_cds > start_nts + stop_nts,
                          list(transcript, length_cds = l_cds)]

  if(start_nts != 0 | stop_nts != 0){
    psite_cds[, length_selection := length_cds - start_nts - stop_nts]
  }

  for (n in names(data)) {
    cat(sprintf("processing %s\n", n))

    data[[n]] <- data[[n]][psite_from_start >= start_nts &
                             psite_from_stop <= -stop_nts &
                             psite_from_start %% 3 == 0]

    temp_count <- data[[n]][, .N, by = transcript]
    psite_cds <- merge(psite_cds, temp_count, by = "transcript", all.x = TRUE)
    setnames(psite_cds, old = "N", new = n)
  }
  return(psite_cds)
}
