#' Plot ribosome occupancy metaprofiles at single-nucleotide resolution.
#'
#' For a specified sample this function generates a metaprofile based on the
#' P-site of the reads mapping around the start and the stop codon of the
#' annotated CDS (if any). It sums up the number of P-sites (defined by their
#' first nucleotide) per nucleotide computed for all the transcripts starting
#' from one ore more replicates.
#'
#' @param data A list of data tables from \code{\link{psite_info}}.
#' @param annotation A data table as generated by
#'   \code{\link{create_annotation}}.
#' @param sample A character string vector specifying the name of the sample (or
#'   of its replicates) of interest. Its elements are merge together using the
#'   scale factors specified by \code{scale_factors}.
#' @param scale_factors A numeric vector of scale factors for merging the
#'   replicates (if any). The vector must contain at least a set of values, one
#'   for each replicates, named after the strings listed in \code{sample}. No
#'   specific order is required. Default is NULL, meaning that all the scale
#'   factors are set to 1.
#' @param length_range Either "all", an integer or an integer vector. Default is
#'   "all", meaning that all the read lengths are included in the analysis.
#'   Otherwise, only the read lengths matching the specified value(s) are kept.
#' @param transcripts A character string vector specifying the name of the
#'   transcripts to be included in the analysis. By default this argument is
#'   NULL, meaning that all the transcripts in \code{data} are used. Note that
#'   if either the 5' UTR, the coding sequence or the 3' UTR of a transcript is
#'   shorther than \code{utr5l}, \eqn{2*}\code{cdsl} and \code{utr3l}
#'   respectively, the transcript is automatically discarded.
#' @param utr5l A positive integer specifying the length (in nucleotides) of the
#'   5' UTR region that in the plot flanks the start codon. The default value is
#'   25.
#' @param cdsl A positive integer specifying the length (in nucleotides) of the
#'   CDS region that in the plot will flank both the start and the stop codon.
#'   The default value is 50.
#' @param utr3l A positive integer specifying the length (in nucleotides) of the
#'   3' UTR region that in the plot flanks the start codon. The default value is
#'   25.
#' @param plot_title Either "auto", NULL or any character string. The default is
#'   "auto", meaning that the title of the plot is the name of the sample
#'   followed by the number of the transcripts and the read lengths considered
#'   for generating the metaprofile.
#' @return A list containing a ggplot2 object, a data table with the associated
#'   data and the transcripts employed for generating the plot.
#' @examples
#' data(reads_psite_list)
#' data(mm81cdna)
#'
#' ## Generate the metaprofile for all the read lengths
#' metaprof_whole <- metaprofile_psite(reads_psite_list, mm81cdna, sample = "Samp1")
#' metaprof_whole[["plot"]]
#'
#' ## Generate the metaprofile employing reads of 27, 28 and 29 nucleotides and
#' a subset of transcripts (for example with at least one P-site mapping on
#' the translation initiation site)
#' sample_name <- "Samp1"
#' sub_reads_psite_list <- subset(reads_psite_list[[sample_name]], psite_from_start == 0)
#' transcript_names <- as.character(sub_reads_psite_list$transcript)
#' metaprof_sub <- metaprofile_psite(reads_psite_list, mm81cdna, sample = sample_name,
#' length_range = 27:29, transcripts = transcript_names)
#' metaprof_sub[["plot"]]
#' @import data.table
#' @import ggplot2
#' @export
metaprofile_psite <- function(data, annotation, sample, scale_factors = NULL,
                              length_range = "all", transcripts = NULL,
                              utr5l = 25, cdsl = 50, utr3l = 25,
                              plot_title = "auto") {
  annotation <- data.frame(annotation)
  rownames(annotation) <- as.character(annotation$transcript)
  l.transcripts <- rownames(annotation)[which(annotation$l_utr5 >= utr5l &
                                                annotation$l_cds >= 2 * (cdsl + 1) &
                                                annotation$l_utr3 >= utr3l)]
  if (length(transcripts) == 0) {
    c.transcripts <- l.transcripts
    ntr <- length(c.transcripts)
  } else {
    c.transcripts <- intersect(l.transcripts, transcripts)
    ntr <- length(transcripts)
  }

  if(!identical(length_range, "all") & !inherits(length_range, "numeric") & !inherits(length_range, "integer")){
    warning("length_range is invalid. Set to default \"all\"\n")
    length_range="all"
  }

  for (samp in sample) {
    data[[samp]] <- data.frame(data[[samp]])
    df <- data[[samp]][which(data[[samp]]$transcript %in% c.transcripts), ]
    if (identical(length_range, "all")) {
      start.sub <- df[which(df$psite_from_start %in% seq(-utr5l, cdsl)), ]
      stop.sub <- df[which(df$psite_from_stop %in% seq(-cdsl, utr3l)), ]
    } else {
      start.sub <- df[which(df$psite_from_start %in% seq(-utr5l, cdsl) & df$length%in%length_range), ]
      stop.sub <- df[which(df$psite_from_stop %in% seq(-cdsl, utr3l) & df$length%in%length_range), ]
    }
    start.tab <- as.data.frame(table(factor(start.sub$psite_from_start, levels = -utr5l:cdsl)))
    start.tab$reg <- "start"
    stop.tab <- as.data.frame(table(factor(stop.sub$psite_from_stop, levels = -cdsl:utr3l)))
    stop.tab$reg <- "stop"
    colnames(start.tab) <- colnames(stop.tab) <- c("distance", "reads", "reg")
    samp.tab <- rbind(start.tab, stop.tab)

    if (length(scale_factors) != 0 & length(scale_factors) == length(sample)) {
      samp.tab$reads <- samp.tab$reads * scale_factors[samp]
    }

    if (exists("final.tab.psitemetaprofile")) {
      final.tab.psitemetaprofile$reads <- final.tab.psitemetaprofile$reads + samp.tab$reads
    } else {
      final.tab.psitemetaprofile <- samp.tab
    }
  }
  final.tab.psitemetaprofile$reg <- factor(final.tab.psitemetaprofile$reg, levels = c("start", "stop"), labels = c("Distance from start (nt)", "Distance from stop (nt)"))

  linestart <- data.frame(reg = rep(c("Distance from start (nt)", "Distance from stop (nt)"), times = c(length(c(rev(seq(-3, -utr5l, -3)), seq(3, cdsl, 3))), length(c(rev(seq(-2, -cdsl, -3)), seq(1, utr3l, 3))))), line = c(rev(seq(-3, -utr5l, -3)), seq(3, cdsl, 3), rev(seq(-2, -cdsl, -3)), seq(1, utr3l, 3)))
  linered <- data.frame(reg = c("Distance from start (nt)", "Distance from stop (nt)"), line =c(0, 1))
  
  if(length(plot_title) != 0 && plot_title == "auto"){
    if (identical(length_range, "all")) {
      plot_title <- paste(paste(sample, collapse = "+"), " (", ntr, " tr)", sep = "")
    } else {
      if(min(length_range)==max(length_range)) {
        plot_title <- paste(paste(sample, collapse = "+"), " (", ntr, " tr) - Read length: ", min(length_range), " nts", sep = "")
      } else {
        if(identical(length_range, min(length_range):max(length_range)) | identical(length_range, seq(min(length_range),max(length_range),1))){
          plot_title <- paste(paste(sample, collapse = "+"), " (", ntr, " tr) - Read lengths: ", min(length_range), "-", max(length_range), " nts",sep = "")
        } else {
          plot_title <- paste(paste(sample, collapse = "+"), " (", ntr, " tr) - Read lengths: ", paste(length_range, collapse=","), " nts",sep = "")
        }
      }
    }
  }

  plot <- ggplot(final.tab.psitemetaprofile, aes(as.numeric(as.character(distance)), reads)) +
    geom_line(size=1.05, color="gray40") +
    geom_vline(data = linered, aes(xintercept = line), linetype = 1, color = "red") +
    labs(x = "", y = "P-site", title = plot_title) +
    theme_bw(base_size = 20) +
    theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
    facet_grid(. ~ reg, scales = "free", switch = "x") +
    theme(strip.background = element_blank(), strip.placement = "outside") +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_vline(data = linestart, aes(xintercept = line), linetype = 3, color = "gray60")
  plot

  output <- list()
  output[["plot"]] <- plot
  output[["dt"]] <- data.table(final.tab.psitemetaprofile)
  output[["transcripts"]] <- c.transcripts
  return(output)
}

#' Plot ribosome occupancy metaheatmaps at single-nucleotide resolution.
#'
#' For one or more sample this function plots a heatmap-like metaprofile based
#' on the P-site of the reads mapping around the start and the stop codon of the
#' annotated CDS (if any). It works similarly to \code{\link{metaprofile_psite}}
#' but the intensity of the signal is represented by a continuous color scale
#' rather than by the height of a line chart. This graphical output is a good
#' option for analyzing several samples at once and for comparing the profiles
#' generated by different reads lengths or in multiple conditions.
#'
#' @param data A list of data tables from \code{\link{psite_info}}.
#' @param annotation A data table as generated by
#'   \code{\link{create_annotation}}.
#' @param sample A list of character string vectors specifying the name of the
#'   samples (or of its replicates) of interest. The elements of each vector are
#'   merge together using the scale factors specified by \code{scale_factors}.
#'   The name of the elements of the list are used for labelling the raws of the
#'   heatmap.
#' @param scale_factors A numeric vector of scale factors for merging the
#'   replicates (if any). The vector must contain at least a set of values, one
#'   for each replicates, named after the strings listed in \code{sample}. No
#'   specific order is required. Default is NULL, meaning that all the scale
#'   factors are set to 1.
#' @param length_range Either "all", an integer or an integer vector. Default is
#'   "all", meaning that all the read lengths are included in the analysis.
#'   Otherwise, only the read lengths matching the specified value(s) are kept.
#' @param transcripts A character string vector specifying the name of the
#'   transcripts to be included in the analysis. By default this argument is
#'   NULL, meaning that all the transcripts in \code{data} are used. Note that
#'   if either the 5' UTR, the coding sequence or the 3' UTR of a transcript is
#'   shorther than \code{utr5l}, \eqn{2*}\code{cdsl} and \code{utr3l}
#'   respectively, the transcript is automatically discarded.
#' @param utr5l A positive integer specifying the length (in nucleotides) of the
#'   5' UTR region that in the plot flanks the start codon. The default value is
#'   25.
#' @param cdsl A positive integer specifying the length (in nucleotides) of the
#'   CDS region that in the plot will flank both the start and the stop codon.
#'   The default value is 50.
#' @param utr3l A positive integer specifying the length (in nucleotides) of the
#'   3' UTR region that in the plot flanks the start codon. The default value is
#'   25.
#' @param log A logical value whether or not to use a logarithmic scale colour
#'   (strongly suggested in case of large variations of the signal). Default is
#'   FALSE.
#' @param colour A character string specifying the colour of the plot. Default
#'   is "black".
#' @param plot_title Either "auto", NULL or any character string. The default is
#'   "auto", meaning that the title of the plot is the name of the sample
#'   followed by the number of the transcripts and the read lengths considered
#'   for generating the metaprofile.
#' @return A list containing a ggplot2 object, a data table with the associated
#'   data and the transcripts employed for generating the plot.
#' @examples
#' data(reads_psite_list)
#'
#' ## Generate the metaheatmap for all the read lengths
#' metaheat_whole <- metaheatmap_psite(reads_psite_list, mm81cdna, sample = list("Whole"=c("Samp1")))
#' metaheat_whole[["plot"]]
#'
#' ## Generate the metaheatmap employing reads of 27, 28 and 29 nucleotides and
#' a subset of transcripts (for example with at least one P-site mapping on the
#' translation initiation site)
#' sample_name <- "Samp1"
#' sub_reads_psite_list <- subset(reads_psite_list[[sample_name]], psite_from_start == 0)
#' transcript_names <- as.character(sub_reads_psite_list$transcript)
#' metaheat_sub <- metaheatmap_psite(reads_psite_list, mm81cdna, sample = list("sub"=sample_name),
#' length_range = 27:29, transcripts = transcript_names, plot_title = "auto")
#' metaheat_sub[["plot"]]
#'
#' ## Generate two metaheatmaps displaied in the same plot. In this exampe one
#' data table includes all the read lengths while in the other one contains only
#' reads of 28 nucleotides
#' sample_name <- "Samp1"
#' metaheat_df <- list()
#' metaheat_df[["subsample_28nt"]] <- subset(reads_psite_list[[sample_name]], length == 28)
#' metaheat_df[["whole_sample"]] <- reads_psite_list[[sample_name]]
#' names_list <- list("Only_28" = c("subsample_28nt"), "All" = c("whole_sample"))
#' metaheat_comparison <- metaheatmap_psite(metaheat_df, mm81cdna, sample = names_list)
#' metaheat_comparison[["plot"]]
#' @import data.table
#' @import ggplot2
#' @export
metaheatmap_psite <- function(data, annotation, sample, scale_factors = NULL,
                              length_range = "all", transcripts = NULL,
                              utr5l = 25, cdsl = 50, utr3l = 25, log = F,
                              colour = "black", plot_title = NULL) {
  annotation <- data.frame(annotation)
  rownames(annotation) <- as.character(annotation$transcript)
  l.transcripts <- rownames(annotation)[which(annotation$l_utr5 >= utr5l &
                                                annotation$l_cds >= 2 * (cdsl + 1) &
                                                annotation$l_utr3 >= utr3l)]
  if (length(transcripts) == 0) {
    c.transcripts <- l.transcripts
    ntr <- length(c.transcripts)
  } else {
    c.transcripts <- intersect(l.transcripts, transcripts)
    ntr <- length(transcripts)
  }

  if(!identical(length_range, "all") & !inherits(length_range, "numeric") & !inherits(length_range, "integer")){
    warning("length_range is invalid. Set to default \"all\" \n")
    length_range="all"
  }

  if(inherits(length_range, "numeric") | inherits(length_range, "integer")){
    for(sampgroup in names(sample)){
      len_check_vec <- numeric()
      for(samp in sample[[sampgroup]]){
        len_check <- unique(data[[samp]]$length)
        if(sum(length_range %in% len_check) == 0) {
          warning(sprintf("data table \"%s\" does not contain reads of the specified lengths \n", samp))
        }
        len_check_vec <- c(len_check_vec, len_check)
      }
      if(sum(length_range %in% len_check_vec) == 0) {
        sample[[sampgroup]] <- NULL
        warning(sprintf("none of the data tables in \"%s\" contain reads of the specified lengths: sample \"%s\" will not be considered \n", sampgroup, sampgroup))
      }
    }
  }

  for(sampgroup in names(sample)){
    for (samp in sample[[sampgroup]]) {
      data[[samp]] <- data.frame(data[[samp]])
      df <- data[[samp]][which(data[[samp]]$transcript %in% c.transcripts), ]
      if (identical(length_range, "all")) {
        start.sub <- df[which(df$psite_from_start %in% seq(-utr5l, cdsl)), ]
        stop.sub <- df[which(df$psite_from_stop %in% seq(-cdsl, utr3l)), ]
      } else {
        start.sub <- df[which(df$psite_from_start %in% seq(-utr5l, cdsl) & df$length%in%length_range), ]
        stop.sub <- df[which(df$psite_from_stop %in% seq(-cdsl, utr3l) & df$length%in%length_range), ]
      }
      start.tab <- as.data.frame(table(factor(start.sub$psite_from_start, levels = -utr5l:cdsl)))
      start.tab$reg <- "start"
      stop.tab <- as.data.frame(table(factor(stop.sub$psite_from_stop, levels = -cdsl:utr3l)))
      stop.tab$reg <- "stop"
      colnames(start.tab) <- colnames(stop.tab) <- c("distance", "reads", "reg")
      samp.tab <- rbind(start.tab, stop.tab)

      if (length(scale_factors) != 0 & length(scale_factors) == length(sample)) {
        samp.tab$reads <- samp.tab$reads * scale_factors[samp]
      }

      if (exists("temp.tab.heatmap")) {
        temp.tab.heatmap$reads <- temp.tab.heatmap$reads + samp.tab$reads
      } else {
        temp.tab.heatmap <- samp.tab
      }
      temp.tab.heatmap$sample <- sampgroup
    }

    if (exists("final.tab.heatmap")) {
      final.tab.heatmap <- rbind(final.tab.heatmap, temp.tab.heatmap)
    } else {
      final.tab.heatmap <- temp.tab.heatmap
    }
    rm(temp.tab.heatmap)
  }

  final.tab.heatmap$reg <- factor(final.tab.heatmap$reg, levels = c("start", "stop"), labels = c("Distance from start (nt)", "Distance from stop (nt)"))
  final.tab.heatmap$sample <- factor(final.tab.heatmap$sample, levels = rev(unique(final.tab.heatmap$sample)))

  linestart <- data.frame(reg = rep(c("Distance from start (nt)", "Distance from stop (nt)"), times = c(length(c(rev(seq(-3, -utr5l, -3)), seq(3, cdsl, 3))), length(c(rev(seq(-2, -cdsl, -3)), seq(1, utr3l, 3))))), line = c(rev(seq(-3, -utr5l, -3)), seq(3, cdsl, 3), rev(seq(-2, -cdsl, -3)), seq(1, utr3l, 3)))
  linered <- data.frame(reg = c("Distance from start (nt)", "Distance from stop (nt)"), line =c(0, 1))

  if(length(plot_title) != 0 && plot_title == "auto"){
    if (identical(length_range, "all")) {
      plot_title <- paste(ntr, " tr", sep = "")
    } else {
      if(min(length_range)==max(length_range)) {
        plot_title <- paste(ntr, " tr - Read length: ", min(length_range), " nts", sep = "")
      } else {
        if(identical(length_range, min(length_range):max(length_range)) | identical(length_range, seq(min(length_range),max(length_range),1))){
          plot_title <- paste(ntr, " tr - Read lengths: ", min(length_range), "-", max(length_range), " nts",sep = "")
        } else {
          plot_title <- paste(ntr, " tr - Read lengths: ", paste(length_range, collapse=","), " nts",sep = "")
        }
      }
    }
  }

  max <- max(final.tab.heatmap$reads)

  plot <- ggplot(final.tab.heatmap, aes(as.numeric(as.character(distance)), sample)) +
    geom_vline(data = linestart, aes(xintercept = line), linetype = 3, color = "gray60") +
    geom_vline(data = linered, aes(xintercept = line), linetype = 1, color = "red") +
    geom_tile(aes(fill = reads), height = 0.7) +
    labs(x = "", y = "", title = plot_title) +
    theme_bw(base_size = 20) +
    theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), strip.placement = "outside") +
    facet_grid(. ~ reg, scales = "free", switch = "x") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(strip.background = element_blank())

  if (log == F) {
    plot <- plot +
      scale_fill_gradient("P-site signal\n", low = "white", high = colour, limits = c(0.1, max), breaks = c(0.1, max/2, max), labels = c("0", floor(max/2), floor(max)), na.value = "white")
  } else {
    plot <- plot +
      scale_fill_gradient("P-site signal\n", low = "white", high = colour, limits = c(0.1, max), breaks = c(0.1, 10^(log10(max)/2 - 0.5), floor(max)), labels = c("0", floor(10^(log10(max)/2 - 0.5)), floor(max)), trans = "log", na.value = "transparent")
  }

  output <- list()
  output[["plot"]] <- plot
  output[["dt"]] <- data.table(final.tab.heatmap)
  output[["transcripts"]] <- c.transcripts
  return(output)
}
