#' Percentage of P-sites per transcript region.
#' 
#' This function computes the percentage of P-sites falling in the three
#' annotated regions of the transcripts (5' UTR, CDS and 3' UTR) and generates a
#' bar plot of the resulting values.
#' 
#' @param data Either list of data tables or GRangesList object from
#'   \code{\link{psite_info}}.
#' @param annotation Data table as generated by \code{\link{create_annotation}}.
#' @param sample Character string vector specifying the name of the sample(s) of
#'   interest. Default is NULL i.e. all samples in \code{data} are processed.
#' @param transcripts Character string vector listing the name of transcripts to
#'   be included in the analysis. Default is NULL i.e. all transcripts are used.
#'   Please note: transcripts without annotated 5' UTR, CDS and 3' UTR are
#'   automatically discarded.
#' @param label_sample Named character string vector the same length as
#'   \code{sample} specifying the sample names to be displayed in the plot.
#'   Plase be careful to name each element of the vector after the correct
#'   corresponding string in \code{sample}. No specific order is required.
#'   Default is NULL i.e. sample names in \code{sample} are used.
#' @param colour Character string vector of three elements specifying the colour
#'   for the 5' UTR, CDS and 3' UTR bars, respectively. Default is a grayscale.
#' @details Column "RNAs" reports the percentage of region length for the
#'   transcripts included in the analysis, based on the cumulative nucleotide
#'   length of 5' UTRs, CDSs and 3' UTRs. These values reflect the expected read
#'   distribution from a random fragmentation of RNA and can be used as a
#'   baseline to verify the expected enrichment of ribosome (P-site) signal in
#'   CDSs.
#' @return A list containing a ggplot2 object ("plot") and the data table with
#'   the associated data ("dt").
#' @examples
#' ## data(reads_list)
#' ## data(mm81cdna)
#' ##
#' ## ## compute and add p-site datails
#' ## psite_offset <- psite(reads_list, flanking = 6, extremity = "auto")
#' ## reads_psite_list <- psite_info(reads_list, psite_offset)
#' ##
#' ## reg_psite <- region_psite(reads_psite_list, mm81cdna, sample = "Samp1")
#' ## reg_psite[["plot"]]
#' @import data.table
#' @import ggplot2
#' @export
region_psite <- function(data, annotation, sample = NULL, transcripts = NULL,
                         label_sample = NULL,
                         colour = c("gray70", "gray40", "gray10")) {
  
  if(class(data[[1]])[1] == "GRanges"){
    data_tmp <- list()
    for(i in names(data)){
      data_tmp[[i]] <- as.data.table(data[[i]])[, c("width", "strand") := NULL
                                                ][, seqnames := as.character(seqnames)]
      setnames(data_tmp[[i]], c("seqnames", "start", "end"), c("transcript", "end5", "end3"))
    }
    data <- data_tmp
  }

  l_transcripts <- as.character(annotation[l_utr5 > 0 & 
                                             l_cds > 0 &
                                             l_cds %% 3 == 0 &
                                             l_utr3 > 0, transcript])

  if (length(transcripts) == 0) {
    c_transcript <- l_transcripts
  } else {
    c_transcript <- intersect(l_transcripts, transcripts)
  }
  
  if(length(sample) == 0) {
    sample <- names(data)
  }
  
  if(length(label_sample) == 0) {
    label_sample <- sample
    names(label_sample) <- sample
  }
  
  for(samp in sample) {
    frame_dt <- data[[samp]][as.character(transcript) %in% c_transcript
                             ][, list(count = .N), by = list(region = psite_region)
                               ][, sample := samp
                                 ][, percentage := (count / sum(count)) * 100]
    
    if (exists("melt_table")) {
      melt_table <- rbind(melt_table, frame_dt)
    } else {
      melt_table <- frame_dt
    }
    
  }
  
  melt_table[, class := "mapped"
             ][, sample := factor(sample, levels = unique(sample),
                                  labels = label_sample[unique(sample)])]

  sub_anno <- annotation[as.character(transcript) %in% c_transcript]
  RNA_reg <- colSums(sub_anno[, list(l_utr5, l_cds, l_utr3)])
  RNA_reg_perc <- (RNA_reg / sum(RNA_reg)) * 100
  
  RNA_table <- data.table(region = c("5utr", "cds", "3utr"),
                          percentage = RNA_reg_perc,
                          count = RNA_reg,
                          sample = rep("RNAs", 3),
                          class = "rna")
  
  final_melt_table <- rbind(melt_table, RNA_table)
  final_melt_table <- final_melt_table[, region := factor(region,
                                                          levels = c("5utr", "cds", "3utr"),
                                                          labels = c("5' UTR","CDS","3' UTR"))
                   ][order(region)]
  
  bs <- 25
  bp <- ggplot(final_melt_table,aes(x = sample, y = percentage, fill = region)) +
    geom_bar(stat = "identity",color = "white",width = 0.65, alpha = 0.9, size = 0.025 * bs) +
    scale_fill_manual(name = "", values = colour) +
    theme_bw(base_size = bs) +
    theme(legend.key = element_blank()) +
    theme(axis.title.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.x = element_blank()) +
    scale_x_discrete(breaks = unique(final_melt_table$sample)) +
    facet_grid( . ~ class, scales = "free", space="free_x") +
    theme(strip.background = element_blank(), strip.text = element_blank()) +
    scale_y_continuous("P-sites (%)", sec.axis = sec_axis(~ . * 1 , name = "Length (%)")) + 
    theme(legend.position = "top", legend.margin=margin(0,0,-5,0), legend.box.margin=margin(5,0,-10,0)) +
    theme(legend.text = element_text(margin = margin(l = -10, unit = "pt")))
  
  output <- list()
  output[["plot"]] <- bp
  output[["dt"]] <- final_melt_table
  return(output)
}

















