#' Compute the number of in-frame P-sites per coding sequence.
#'
#' For each sample and each transcript this function computes the number of
#' P-sites in frame 0 within the coding sequence. It is possible to exclude
#' from the analysis a specified number of nucleotides at the beginiing and/or
#' at the end of the CDS, restricting the analysis to a subsequence of the
#' coding region. Please note that only the transcripts associated to an
#' annotated CDS are kept for the analysis. The resulting data table reports the
#' name of the transripts along with the length of the considered region (in
#' nucleotides) and the associated number of P-sites for all the samples.
#'
#' @param data A list of data tables from \code{\link{psite_info}}.
#' @param annotation A data table as generated by
#'   \code{\link{create_annotation}}.
#' @param start_nts A positive integer specifying the number of nucleotides at
#'   the beginning of the coding sequences to be exluded from the analisys
#'   Default is 0.
#' @param stop_nts A positive integer specifying the number of nucleotides at
#'   the end of the coding sequences to be exluded from the analisys. Default is
#'   0.
#' @return A data table.
#' @examples
#' data(reads_psite_list)
#' data(mm81cdna)
#'
#' ## Compute the number of P-sites in frame on the whole coding sequence.
#' psite_cds <- psite_per_cds(reads_psite_list, mm81cdna)
#'
#' ## Compute the number of P-sites in frame on the coding sequence exluding
#' the first 15 nucleotides and the last 10 nucleotides.
#' psite_cds <- psite_per_cds(reads_psite_list, mm81cdna, start_nts = 15, stop_nts = 10)
#' @import data.table
#' @export
psite_per_cds <- function(data, annotation, start_nts = 0, stop_nts = 0) {
  
  psite_cds <- annotation[l_cds > start_nts + stop_nts,
                          list(transcript, length = l_cds - start_nts - stop_nts)]
  
  for (n in names(data)) {
    cat(sprintf("processing %s\n", n))
    
    data[[n]][, transcript := factor(transcript, levels = as.character(psite_cds$transcript))]
    data[[n]] <- data[[n]][as.character(transcript) %in% as.character(psite_cds$transcript) &
                             psite_from_start >= start_nts &
                             psite_from_stop <= -stop_nts &
                             psite_from_start %% 3 == 0]
    setkey(data[[n]], "transcript")
    psite_cds[ , (n) := (data[[n]][CJ(levels(transcript)), .N, by = .EACHI]$N)] 
    
  }
  return(psite_cds)
}
