#' Plot metaheatmaps based on the two extremities of the reads.
#'
#' For a specified sample this function plots four metaheatmaps showing the
#' abundance of the 5' and the 3' end of the reads mapping around the start and
#' the stop codon of the annotated CDS (if any), stratified by their length. It
#' is possible to visualise the metaheatmaps for all the read lengths or to
#' restrict the graphical output to a sub-range of read lengths.
#'
#' @param data A list of data frames from either \code{\link{bamtolist}} or
#'   \code{\link{bedtolist}}.
#' @param annotation A data frame as generated by
#'   \code{\link{create_annotation}}.
#' @param sample A character string specifying the name of the sample of
#'   interest.
#' @param transcripts A character string vector specifying the name of the
#'   transcripts to be included in the analysis. By default this argument is
#'   NULL, meaning that all the transcripts in \code{data} are used. Note that
#'   if either the 5' UTR, the coding sequence or the 3' UTR of a transcript is
#'   shorther than \code{utr5l}, \eqn{2*}\code{cdsl} and \code{utr3l}
#'   respectively, the transcript is automatically discarded.
#' @param cl An integer value in \emph{[1,100]} specifying the confidence level
#'   for restricting the plot to a sub-range of read lengths. By default it is
#'   set to 99.
#' @param utr5l A positive integer specifying the length (in nucleotides) of the
#'   5' UTR region that in the plot flanks the start codon. The default value is
#'   50.
#' @param cdsl A positive integer specifying the length (in nucleotides) of the
#'   CDS region that in the plot will flank both the start and the stop codon.
#'   The default value is 50.
#' @param utr3l A positive integer specifying the length (in nucleotides) of the
#'   3' UTR region that in the plot flanks the start codon. The default value is
#'   50.
#' @param log A logical value whether or not to use a logarithmic scale colour
#'   (strongly suggested in case of large variations of the signal). Default is
#'   FALSE.
#' @param colour A character string specifying the colour of the plot. Default
#'   is "black".
#' @return A list containing a ggplot2 object, and a data frame with the
#'   associated data.
#' @examples
#' data(reads_list)
#' data(mm81cdna)
#'
#' ## Visualise the metaheatmaps for all the read lengths
#' heatend_whole <- rends_heat(reads_list, mm81cdna, sample = "Samp1", cl = 100)
#' heatend_whole[["plot"]]
#'
#' ## Visualise the metaheatmaps for a sub-range of read lengths (the middle
#' 95%) reducing the flanking regions around the start and the stop codon
#' heatend_sub95 <- rends_heat(reads_list, mm81cdna, sample = "Samp1", cl = 95,
#' utr5l = 30, cdsl = 40, utr3l = 30)
#' heatend_sub95[["plot"]]
#' @import ggplot2
#' @export
rends_heat <- function(data, annotation, sample, transcripts = NULL, cl = 99, utr5l = 50, cdsl = 50, utr3l = 50,
                       log = F, colour = "black") {
  df <- data[[sample]]
  df$start.dist.end5 <- df$end5 - df$start_pos
  df$stop.dist.end5 <- df$end5 - df$stop_pos
  df$start.dist.end3 <- df$end3 - df$start_pos
  df$stop.dist.end3 <- df$end3 - df$stop_pos
  minlen <- ceiling(quantile(df$length, (1 - cl/100)/2))
  maxlen <- ceiling(quantile(df$length, 1 - (1 - cl/100)/2))
  
  rownames(annotation) <- as.character(annotation$transcript)
  l.transcripts <- rownames(annotation)[which(annotation$l_utr5 >= utr5l &
                                                annotation$l_cds >= 2 * (cdsl + 1) &
                                                annotation$l_utr3 >= utr3l)]
  if (length(transcripts) == 0) {
    c.transcripts <- l.transcripts
  } else {
    c.transcripts <- intersect(l.transcripts, transcripts)
  }
  
  df <- subset(df, as.character(transcript) %in% c.transcripts)
  
  # 5' end
  start.sub <- df[which(df$start.dist.end5 %in% seq(-utr5l, cdsl)), ]
  stop.sub <- df[which(df$stop.dist.end5 %in% seq(-cdsl, utr3l)), ]
  start.tab <- aggregate(rep(1, nrow(start.sub)), by = list(x = start.sub$length, y = start.sub$start.dist.end5), sum, drop = F)
  stop.tab <- aggregate(rep(1, nrow(stop.sub)), by = list(x = stop.sub$length, y = stop.sub$stop.dist.end5), sum, drop = F)
  colnames(start.tab) <- colnames(stop.tab) <- c("length", "dist", "count")
  start.tab$region <- "start"
  stop.tab$region <- "stop"
  final.tab5 <- rbind(start.tab, stop.tab)
  final.tab5$end <- "5end"
  
  # 3' end
  start.sub <- df[which(df$start.dist.end3 %in% seq(-utr5l, cdsl)), ]
  stop.sub <- df[which(df$stop.dist.end3 %in% seq(-cdsl, utr3l)), ]
  start.tab <- aggregate(rep(1, nrow(start.sub)), by = list(x = start.sub$length, y = start.sub$start.dist.end3), sum, drop = F)
  stop.tab <- aggregate(rep(1, nrow(stop.sub)), by = list(x = stop.sub$length, y = stop.sub$stop.dist.end3), sum, drop = F)
  colnames(start.tab) <- colnames(stop.tab) <- c("length", "dist", "count")
  start.tab$region <- "start"
  stop.tab$region <- "stop"
  final.tab3 <- rbind(start.tab, stop.tab)
  final.tab3$end <- "3end"
  
  final.tab <- rbind(final.tab5, final.tab3)
  final.tab$region <- factor(final.tab$region, levels = c("start", "stop"), labels = c("Distance from start (nt)", "Distance from stop (nt)"))
  final.tab$end <- factor(final.tab$end, levels = c("5end", "3end"), labels = c("5' end", "3' end"))
  
  max<-max(final.tab$count)
  p <- ggplot(final.tab, aes(dist, length)) +
    geom_tile(aes(fill = count)) +
    labs(title = paste(sample, "5' / 3' read end metaheatmaps", sep = " - "), y = "Read length") +
    theme_bw(base_size = 20) +
    theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank(), axis.title.x = element_blank()) +
    facet_grid(end ~ region, scales = "free", switch = "x") +
    theme(strip.background = element_blank(), strip.placement = "outside") +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_y_continuous(limits = c(minlen-0.5, maxlen+0.5), breaks = seq(minlen + ((minlen) %% 2), maxlen, by=max(2,floor((maxlen-minlen)/7)))) +
    geom_vline(xintercept = 0, linetype = 2, color = "red")
  
  if (log == F) {
    p <- p +
      scale_fill_gradient("Number\nof read\nextremities\n", low = "white", high = colour, limits = c(0.1, max), breaks = c(0.1, max/2, max), labels = c("0", floor(max/2), floor(max)), na.value = "white")
  } else {
    p <- p +
      scale_fill_gradient("Number\nof read\nextremities\n", low = "white", high = colour, limits = c(0.1, max), breaks = c(0.1, 10^(log10(max)/2 - 0.5), floor(max)), labels = c("0", floor(10^(log10(max)/2 - 0.5)), floor(max)), trans = "log", na.value = "transparent")
  }
  
  output<-list()
  output[["plot"]]<-p
  output[["df"]]<-final.tab
  return(output)
}
